"""Added the ToDoList Model

Revision ID: 1f7137e99199
Revises: 
Create Date: 2026-06-25 10:04:17.934140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f7137e99199'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('to_do_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('iscompleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('posts')
    # op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('users',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    # sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    # sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    # sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    # )
    # op.create_table('posts',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('content', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('posts_user_id_fkey'), ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id', name=op.f('posts_pkey'))
    # )
    op.drop_table('to_do_list')
    # ### end Alembic commands ###
