"""Change the column name in ToDoList Model

Revision ID: d02bd7a5cdb4
Revises: 1f7137e99199
Create Date: 2026-06-25 10:11:20.415062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd02bd7a5cdb4'
down_revision: Union[str, Sequence[str], None] = '1f7137e99199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('users')
    # op.drop_table('posts')
    op.add_column('to_do_list', sa.Column('task_title', sa.String(), nullable=False))
    op.drop_column('to_do_list', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('to_do_list', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('to_do_list', 'task_title')
    # op.create_table('posts',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('content', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('posts_user_id_fkey'), ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id', name=op.f('posts_pkey'))
    # )
    # op.create_table('users',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    # sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    # sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    # sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    # )
    # ### end Alembic commands ###
